language: node_js

node_js:
  - "node"

# before_install:
#  - pip install --user codecov

script:
  - npm run build
  - npm run lint
  - npm run test

#after_success:
#  - codecov --file coverage/apps/dcs-admin/lcov.info --disable search
#  - codecov --file coverage/apps/dcs-frontend/lcov.info --disable search
