version: '3'

services:
  database:
    image: mongo:4.0.13
    restart: always
    networks:
      - learn_network
    volumes:
      - $DB_DATA_PATH:/data/db

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - learn_network

  learn_to_code:
    depends_on:
      - database
      - redis
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - $RESOURCES_DATA_PATH:/app/resources
    ports:
      - '127.0.0.1:4555:80'
    networks:
      - learn_network

networks:
  learn_network:
    external: true
